# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-21 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RssItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, help_text='Title of rss item', null=True)),
                ('summary', models.TextField(blank=True, help_text='Body of rss item', null=True)),
                ('link', models.CharField(help_text='link to content', max_length=300, unique=True)),
                ('updated', models.DateTimeField(blank=True, help_text='date updated utc', null=True)),
            ],
        ),
    ]
